spring:
  application:
    name: demo
#  main:
#    web-application-type: none
  ai:
    ollama:
      chat:
        options:
#          model: gpt-oss:20b
          model: exaone3.5:7.8b
      embedding:
        options:
          model: qwen3-embedding:8b
    vectorstore:
      mariadb:
        initialize-schema: true
  datasource:
    url: jdbc:mariadb://localhost:3307/mydb
    username: myuser
    password: mypass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true